image: gitlab-registry.cern.ch/ecalpfg/dqmcpp:ci

default:
 cache:
   paths:
    - "**/*.o"
    - "dqmcache"

build:
  stage: build
  script:
    - mkdir -p build
    - cd build
    - cmake -DPFGPLUGINS=ON ../src
    - make
